In [2]:
import numpy as np
#1:8*8棋盘矩阵，其中1、3、5、7行&&0、2、4、6列的元素置为1   1 ,3，5，7列&&0,2,4,6行也是1
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
z = np.random.random((10,10))
zmin,zmax = z.min(),z.max()

In [3]:
#归一化，将矩阵规格化到0～1，即最小的变成0，最大的变成1，最小与最大之间的等比缩放
z = 10*np.random.random((5,5))
print(z)
zmin,zmax = z.min(),z.max()
z = (z-zmin)/(zmax-zmin)
print (z)

[[ 4.55212547  5.46185262  8.60004373  1.93478233  4.65510502]
 [ 2.53768646  4.05693993  2.19796445  1.07345801  6.20812085]
 [ 0.49021813  2.82883742  2.16880837  6.33642935  9.68820436]
 [ 8.10942278  1.00812598  4.11000806  0.44159926  1.97445129]
 [ 2.07217331  1.84092051  9.07186064  3.96425218  0.28653753]]
[[ 0.4537055   0.55046782  0.88425875  0.1753141   0.46465883]
 [ 0.23944147  0.40103553  0.20330724  0.0837001   0.62984399]
 [ 0.02166431  0.27040949  0.20020608  0.64349141  1.        ]
 [ 0.83207429  0.07675112  0.40668007  0.016493    0.17953346]
 [ 0.18992757  0.16533057  0.93444314  0.39117687  0.        ]]


In [14]:
#矩阵相加
z = np.zeros((5,5))
z += np.arange(5)
print np.arange(5)
print z


[0 1 2 3 4]
[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [16]:
#生成0~10之间均匀分布的11个数，包括0和10

z = np.linspace(0,10,11,endpoint=True,retstep=True)
print z


(array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]), 1.0)


In [18]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo